"""MLB Player → Team lookup table. 150+ players with actual 2025/2026 affiliations.
Used by both generate_projections.py (fallback) and daily_picks.py (correct_team).
"""

MLB_PLAYER_TEAMS = {
    # AL East
    "Aaron Judge": "NYY",
    "Giancarlo Stanton": "NYY",
    "Anthony Volpe": "NYY",
    "Cody Bellinger": "NYY",
    "Jasson Dominguez": "NYY",
    "Jazz Chisholm": "NYY",
    "Paul Goldschmidt": "NYY",
    "Austin Wells": "NYY",
    "Gunnar Henderson": "BAL",
    "Adley Rutschman": "BAL",
    "Colton Cowser": "BAL",
    "Jordan Westburg": "BAL",
    "Ryan Mountcastle": "BAL",
    "Cedric Mullins": "BAL",
    "Jackson Holliday": "BAL",
    "Rafael Devers": "BOS",
    "Jarren Duran": "BOS",
    "Alex Bregman": "BOS",
    "Triston Casas": "BOS",
    "Trevor Story": "BOS",
    "Masataka Yoshida": "BOS",
    "Wilyer Abreu": "BOS",
    "Vladimir Guerrero": "TOR",
    "Bo Bichette": "TOR",
    "George Springer": "TOR",
    "Anthony Santander": "TOR",
    "Andres Gimenez": "TOR",
    "Alejandro Kirk": "TOR",
    "Daulton Varsho": "TOR",
    "Yandy Diaz": "TB",
    "Brandon Lowe": "TB",
    "Junior Caminero": "TB",
    "Randy Arozarena": "TB",
    "Josh Lowe": "TB",
    "Carson Williams": "TB",

    # AL Central
    "Jose Ramirez": "CLE",
    "Steven Kwan": "CLE",
    "Kyle Manzardo": "CLE",
    "Brayan Rocchio": "CLE",
    "Lane Thomas": "CLE",
    "Luis Robert": "CHW",
    "Andrew Vaughn": "CHW",
    "Andrew Benintendi": "CHW",
    "Colson Montgomery": "CHW",
    "Bobby Witt": "KC",
    "Salvador Perez": "KC",
    "Vinnie Pasquantino": "KC",
    "MJ Melendez": "KC",
    "Maikel Garcia": "KC",
    "Riley Greene": "DET",
    "Spencer Torkelson": "DET",
    "Kerry Carpenter": "DET",
    "Parker Meadows": "DET",
    "Colt Keith": "DET",
    "Byron Buxton": "MIN",
    "Carlos Correa": "MIN",
    "Royce Lewis": "MIN",
    "Brooks Lee": "MIN",
    "Edouard Julien": "MIN",
    "Matt Wallner": "MIN",

    # AL West
    "Yordan Alvarez": "HOU",
    "Jose Altuve": "HOU",
    "Kyle Tucker": "HOU",
    "Jeremy Pena": "HOU",
    "Isaac Paredes": "HOU",
    "Cam Smith": "HOU",
    "Corey Seager": "TEX",
    "Adolis Garcia": "TEX",
    "Marcus Semien": "TEX",
    "Wyatt Langford": "TEX",
    "Josh Jung": "TEX",
    "Evan Carter": "TEX",
    "Julio Rodriguez": "SEA",
    "Cal Raleigh": "SEA",
    "J.P. Crawford": "SEA",
    "Randy Arozarena": "SEA",
    "Luke Raley": "SEA",
    "Mike Trout": "LAA",
    "Shohei Ohtani": "LAD",
    "Logan O'Hoppe": "LAA",
    "Zach Neto": "LAA",
    "Taylor Ward": "LAA",
    "Nolan Schanuel": "LAA",
    "Brent Rooker": "ATH",
    "Lawrence Butler": "ATH",
    "Zack Gelof": "ATH",
    "JJ Bleday": "ATH",
    "Jacob Wilson": "ATH",

    # NL East
    "Ronald Acuna": "ATL",
    "Austin Riley": "ATL",
    "Matt Olson": "ATL",
    "Ozzie Albies": "ATL",
    "Michael Harris": "ATL",
    "Marcell Ozuna": "ATL",
    "Sean Murphy": "ATL",
    "Francisco Lindor": "NYM",
    "Juan Soto": "NYM",
    "Pete Alonso": "NYM",
    "Brandon Nimmo": "NYM",
    "Mark Vientos": "NYM",
    "Francisco Alvarez": "NYM",
    "Bryce Harper": "PHI",
    "Trea Turner": "PHI",
    "Kyle Schwarber": "PHI",
    "Alec Bohm": "PHI",
    "J.T. Realmuto": "PHI",
    "Nick Castellanos": "PHI",
    "Bryson Stott": "PHI",
    "Jazz Chisholm": "MIA",
    "Sandy Alcantara": "MIA",
    "Jesus Sanchez": "MIA",
    "Xavier Edwards": "MIA",
    "CJ Abrams": "WSH",
    "Dylan Crews": "WSH",
    "James Wood": "WSH",
    "Luis Garcia": "WSH",
    "Keibert Ruiz": "WSH",

    # NL Central
    "William Contreras": "MIL",
    "Christian Yelich": "MIL",
    "Jackson Chourio": "MIL",
    "Willy Adames": "MIL",
    "Rhys Hoskins": "MIL",
    "Nolan Arenado": "STL",
    "Lars Nootbaar": "STL",
    "Jordan Walker": "STL",
    "Willson Contreras": "STL",
    "Masyn Winn": "STL",
    "Seiya Suzuki": "CHC",
    "Kyle Tucker": "CHC",
    "Dansby Swanson": "CHC",
    "Ian Happ": "CHC",
    "Nico Hoerner": "CHC",
    "Pete Crow-Armstrong": "CHC",
    "Elly De La Cruz": "CIN",
    "Matt McLain": "CIN",
    "Spencer Steer": "CIN",
    "Jeimer Candelario": "CIN",
    "Noelvi Marte": "CIN",
    "Oneil Cruz": "PIT",
    "Bryan Reynolds": "PIT",
    "Ke'Bryan Hayes": "PIT",
    "Endy Rodriguez": "PIT",

    # NL West
    "Shohei Ohtani": "LAD",
    "Mookie Betts": "LAD",
    "Freddie Freeman": "LAD",
    "Will Smith": "LAD",
    "Max Muncy": "LAD",
    "Teoscar Hernandez": "LAD",
    "Roki Sasaki": "LAD",
    "Fernando Tatis": "SD",
    "Manny Machado": "SD",
    "Jackson Merrill": "SD",
    "Xander Bogaerts": "SD",
    "Luis Arraez": "SD",
    "Corbin Carroll": "ARI",
    "Ketel Marte": "ARI",
    "Gabriel Moreno": "ARI",
    "Eugenio Suarez": "ARI",
    "Geraldo Perdomo": "ARI",
    "Logan Webb": "SF",
    "Matt Chapman": "SF",
    "Jung Hoo Lee": "SF",
    "Willy Adames": "SF",
    "Heliot Ramos": "SF",
    "Nolan Arenado": "STL",
}

def get_mlb_team(player_name: str) -> str:
    """Return correct MLB team abbreviation for a player, or empty string if unknown."""
    return MLB_PLAYER_TEAMS.get(player_name, "")

def correct_mlb_team(player_name: str, current_team: str) -> str:
    """If we have the player in our lookup, return correct team. Otherwise keep current."""
    real = MLB_PLAYER_TEAMS.get(player_name)
    if real:
        return real
    return current_team
