#!/usr/bin/env python3
"""WC player → national team lookup for team correction."""

WC_PLAYER_TEAM_MAP = {
    "Kylian Mbappe": "FRA",
    "Lionel Messi": "ARG",
    "Cristiano Ronaldo": "POR",
    "Erling Haaland": "NOR",
    "Harry Kane": "ENG",
    "Vinicius Jr": "BRA",
    "Jude Bellingham": "ENG",
    "Kevin De Bruyne": "BEL",
    "Mohamed Salah": "EGY",
    "Lamine Yamal": "ESP",
    "Pedri": "ESP",
    "Jamal Musiala": "GER",
    "Lautaro Martinez": "ARG",
    "Julian Alvarez": "ARG",
    "Rodri": "ESP",
    "Federico Valverde": "URU",
    "Neymar": "BRA",
    "Raphinha": "BRA",
    "Phil Foden": "ENG",
    "Bukayo Saka": "ENG",
    "Declan Rice": "ENG",
    "Cole Palmer": "ENG",
    "Trent Alexander-Arnold": "ENG",
    "Antoine Griezmann": "FRA",
    "Ousmane Dembele": "FRA",
    "Eduardo Camavinga": "FRA",
    "Aurelien Tchouameni": "FRA",
    "Theo Hernandez": "FRA",
    "Nico Williams": "ESP",
    "Gavi": "ESP",
    "Dani Olmo": "ESP",
    "Alvaro Morata": "ESP",
    "Florian Wirtz": "GER",
    "Kai Havertz": "GER",
    "Leroy Sane": "GER",
    "Joshua Kimmich": "GER",
    "Rafael Leao": "POR",
    "Bruno Fernandes": "POR",
    "Bernardo Silva": "POR",
    "Joao Felix": "POR",
    "Diogo Jota": "POR",
    "Rodrygo": "BRA",
    "Gabriel Martinelli": "BRA",
}

def correct_wc_team(player_name, current_team):
    return WC_PLAYER_TEAM_MAP.get(player_name, current_team)
