TEAM_ABBREV = {
    "nba": ["ATL","BOS","BKN","CHA","CHI","CLE","DAL","DEN","DET","GSW",
            "HOU","IND","LAC","LAL","MEM","MIA","MIL","MIN","NOP","NYK",
            "OKC","ORL","PHI","PHX","POR","SAC","SAS","TOR","UTA","WAS"],
    "wnba": ["ATL","CHI","CON","DAL","IND","LA","LV","MIN","NY","PHX","SEA","WAS"],
    "mlb": ["ARI","ATL","BAL","BOS","CHC","CIN","CLE","COL","CWS","DET",
            "HOU","KC","LAA","LAD","MIA","MIL","MIN","NYM","NYY","OAK",
            "PHI","PIT","SD","SEA","SF","STL","TB","TEX","TOR","WSH"],
    "nhl": ["ANA","ARI","BOS","BUF","CGY","CAR","CHI","CBJ","COL","DAL",
            "DET","EDM","FLA","LAK","MIN","MTL","NJD","NSH","NYI","NYR",
            "OTT","PHI","PIT","SJS","SEA","STL","TBL","TOR","VAN","VGK",
            "WSH","WPG"],
    "nfl": ["ARI","ATL","BAL","BUF","CAR","CHI","CIN","CLE","DAL","DEN",
            "DET","GB","HOU","IND","JAX","KC","LA","LAC","LV","MIA",
            "MIN","NE","NO","NYG","NYJ","PHI","PIT","SEA","SF","TB",
            "TEN","WAS"],
    "soccer": ["ARS","AVL","BOU","BRE","BRI","CHE","CRY","EVE","FUL","LIV",
               "MCI","MUN","NEW","NFO","SHU","TOT","WHU","WOL","BAR","RMA",
               "ATM","ATH","BET","GET","LEV","RAY","SEV","VAL","VIL","BAY",
               "BOC","BMU","DOR","FRA","HEI","HOF","LEI","STU","UNI","WBG",
               "B04","M05","KOL","BVB","RBL","F95","WOB","AJA","FEY","AJX",
               "PSV","GAL","INT","JUV","MIL","NAP","ROM","LAZ","FIO","ATA"],
    "wc": ["ARG","AUS","AUT","BEL","BOL","BRA","CAN","CHI","CHN","COL",
           "CRC","CRO","CZE","DEN","ECU","EGY","ENG","ESP","FRA","GER",
           "GHA","GRE","HON","IRN","ISL","ITA","JAM","JPN","KOR","KSA",
           "MAR","MEX","NGA","NED","NOR","NZL","PAN","PAR","PER","POL",
           "POR","QAT","ROU","SAU","SEN","SRB","SUI","SWE","TUR","UAE",
           "URU","USA","VEN","WAL","CMR","TUN","CIV","ALG","BIH","SCO",
           "IRL","SVK","UKR","AUT"],
}
