from playwright.sync_api import sync_playwright
import httpx
import uuid
from datetime import datetime
from pathlib import Path


def generate_combo_screenshot(sport: str, date: str) -> str:
    resp = httpx.get(f"http://localhost:8000/live-combos?sport={sport}&date={date}", timeout=10)
    combos_data = resp.json()
    combos = combos_data.get("combos", [])
    seeded = combos_data.get("seeded", False)

    rows_html = "".join(
        f"<tr><td>{i+1}</td><td>{' + '.join(l['player'] for l in c['legs'])}</td>"
        f"<td>{c['total_legs']}</td>"
        f"<td class='edge'>{c['avg_edge']:.1f}</td>"
        f"<td class='conf'>{c['avg_confidence']:.0%}</td>"
        f"<td class='hit'>{c['hit_probability']:.1%}</td></tr>"
        for i, c in enumerate(combos[:20])
    )
    seed_badge = " <span style='background:#ffa726;color:black;padding:2px 8px;border-radius:4px;font-size:12px;'>SEEDED</span>" if seeded else ""

    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial; background: #0f0f1a; color: white; padding: 30px; }}
            h1 {{ color: #ffd54f; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th {{ background: #1a1a2e; padding: 12px; text-align: left; border-bottom: 2px solid #2a2a4e; }}
            td {{ padding: 10px; border-bottom: 1px solid #2a2a4e; }}
            .hit {{ color: #4caf50; font-weight: bold; }}
            .edge {{ color: #ffa726; }}
            .conf {{ color: #4fc3f7; }}
        </style>
    </head>
    <body>
        <h1>🏆 Live Combos — {sport} ({date}){seed_badge}</h1>
        <p style="color: #666;">{len(combos)} qualifying combos found · avg hit {sum(c['hit_probability'] for c in combos)/max(len(combos),1):.1%}</p>
        <table>
            <tr><th>#</th><th>Players</th><th>Legs</th><th>Avg Edge</th><th>Confidence</th><th>Hit Probability</th></tr>
            {rows_html}
        </table>
        <p style="color: #444; margin-top: 30px; font-size: 12px;">Generated by TC Sports • {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
    </body>
    </html>
    """

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page()
        page.set_content(html)
        page.set_viewport_size({"width": 1200, "height": 800 + len(combos) * 30})

        output_dir = Path("/home/workspace/reports/images/combos")
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = output_dir / f"{sport}_{date}_{uuid.uuid4().hex[:8]}.png"
        page.screenshot(path=str(filename), full_page=True)
        browser.close()

    return str(filename)