#!/usr/bin/env python3
"""Build a comprehensive 6th-grade-friendly report of the entire TC pipeline."""
from pathlib import Path
from datetime import datetime

OUT = Path("/home/workspace/Reports/tc_pipeline_explained_6th_grade_20260610.md")

L = []
L.append("# Your Basketball Betting Pipeline — Explained Like You're 12")
L.append("")
L.append("Made on: " + datetime.now().strftime("%Y-%m-%d at %H:%M"))
L.append("")
L.append("Hi! This is a big report that explains every part of your computer program that picks basketball bets. I'll use small words and examples. If anything is confusing, just ask!")
L.append("")
L.append("---")
L.append("")

L.append("# PART 1: What Does This Whole Thing Do?")
L.append("")
L.append("Imagine you and your friends are watching a basketball game. Someone says:")
L.append("")
L.append('"I bet Caitlin Clark scores MORE than 25 points tonight."')
L.append("")
L.append("If you're right, you win money. If you're wrong, you lose money.")
L.append("")
L.append("Doing that once is easy. But what if you wanted to do it for EVERY player, EVERY game, EVERY night? And what if you wanted to be right MORE than half the time so you actually make money?")
L.append("")
L.append("That's what your pipeline does. It's a robot that:")
L.append("")
L.append("1. Watches basketball games all day")
L.append("2. Reads numbers from the internet (how many points players scored last time, what the betting websites think they'll score)")
L.append("3. Thinks really hard about who is a good bet")
L.append("4. Writes down its guesses")
L.append("5. Checks later if the guesses were right or wrong")
L.append("6. Learns from its mistakes to be smarter next time")
L.append("")
L.append("There are TWO kinds of basketball in this pipeline:")
L.append("")
L.append("- **NBA** — the big boys league, 48-minute games, 30 teams")
L.append("- **WNBA** — the girls league, 40-minute games, 15 teams")
L.append("")
L.append("Your pipeline handles both. The WNBA part is trickier because the games are shorter, so the math is different.")
L.append("")

L.append("---")
L.append("")

L.append("# PART 2: The 4 Big Steps Your Pipeline Takes")
L.append("")
L.append("Think of it like making a sandwich. There are 4 steps:")
L.append("")
L.append("## Step 1: GET THE INGREDIENTS (Collecting Data)")
L.append("")
L.append("Before you can make a guess, you need to know stuff. The pipeline collects 4 kinds of stuff:")
L.append("")
L.append("**A. Who is playing tonight?**")
L.append("")
L.append("The pipeline asks ESPN (a sports website) for the list of games. It gets back things like:")
L.append("- 'Atlanta Dream vs Chicago Sky, June 9, 7pm'")
L.append("- 'New York Liberty vs Connecticut Sun, June 8, 7:30pm'")
L.append("")
L.append("For each game, it finds out which 10-12 players will actually play. Some players are hurt, some are resting, some are 'questionable' (might play, might not).")
L.append("")
L.append("**B. What did each player do in their last 5 games?**")
L.append("")
L.append("The pipeline also asks ESPN for the scorebook from each player's last 5 games. Example for A'ja Wilson:")
L.append("")
L.append("```")
L.append("Game 1: 27 points, 11 rebounds, 3 assists")
L.append("Game 2: 31 points, 9 rebounds, 2 assists")
L.append("Game 3: 24 points, 14 rebounds, 5 assists")
L.append("Game 4: 29 points, 10 rebounds, 4 assists")
L.append("Game 5: 26 points, 12 rebounds, 3 assists")
L.append("```")
L.append("")
L.append("Then it adds those up and finds the average:")
L.append("- Average points: 27.4")
L.append("- Average rebounds: 11.2")
L.append("- Average assists: 3.4")
L.append("")
L.append("**C. What does the betting website think?**")
L.append("")
L.append("There's a website called DraftKings where people bet money. They put a LINE on every player. The line is like a guess THEY'RE making.")
L.append("")
L.append("Example: DraftKings might say:")
L.append("- 'A'ja Wilson: OVER 27.5 points pays -110'")
L.append("  (meaning: if you bet $110, you win $100 if she scores 28 or more)")
L.append("- 'A'ja Wilson: UNDER 27.5 points pays -110'")
L.append("  (meaning: you win $100 if she scores 27 or less)")
L.append("")
L.append("We get these lines from a paid website called The Odds API.")
L.append("")
L.append("**D. What time does the game start?**")
L.append("")
L.append("This matters because we need to know if the game already happened (so we can check if we were right) or if it's in the future (so we should make a new guess).")
L.append("")

L.append("## Step 2: MAKE A GUESS (The TC Math)")
L.append("")
L.append("Now the pipeline uses a special formula called TC (Triple Conservative) to figure out what it thinks each player will do. Here's the idea:")
L.append("")
L.append("1. Take the player's average from the last 5 games")
L.append("2. Shrink it a little bit (this is called 'Bayesian shrinkage' — fancy words for 'don't trust the small sample TOO much')")
L.append("3. Multiply by a 'be safe' number (0.85 means 'play a little safer than the average')")
L.append("4. If it's WNBA, multiply by 0.833 (because WNBA games are 40 minutes instead of 48)")
L.append("")
L.append("Example: A'ja Wilson's TC projection for tonight:")
L.append("- Start: average 27.4 points")
L.append("- Shrink toward league average: 27.0")
L.append("- Multiply by 0.85 (be safe): 22.95")
L.append("- Multiply by 0.833 (WNBA): 19.12")
L.append("")
L.append("Wait, that's TOO LOW. We learned this! In real life, the projection was about 19 but she actually scored 27. The pipeline was way too pessimistic.")
L.append("")
L.append("**Combo Props** are special bets where you add up 2 or 3 stats:")
L.append("- **PRA** = Points + Rebounds + Assists")
L.append("- **PR** = Points + Rebounds (no assists)")
L.append("- **PA** = Points + Assists (no rebounds)")
L.append("")
L.append("The DraftKings lines for combos are like 'A'ja Wilson OVER 38.5 PRA' — meaning the bet wins if she gets 39 or more combined points+rebounds+assists.")
L.append("")
L.append("The pipeline tries to figure out:")
L.append("1. What it thinks the player will do (TC projection)")
L.append("2. How that compares to DraftKings' line")
L.append("3. Whether to bet OVER or UNDER")
L.append("")

L.append("## Step 3: SAY IT OUT LOUD (The Output)")
L.append("")
L.append("After all the math, the pipeline makes a list of picks. Each pick looks like:")
L.append("")
L.append("```")
L.append("Player: A'ja Wilson")
L.append("Team: Las Vegas Aces")
L.append("Stat: PRA (points + rebounds + assists)")
L.append("DraftKings line: 38.5")
L.append("TC projection: 32.1")
L.append("Recommendation: UNDER (because TC thinks 32 is way less than DK's 38.5)")
L.append("Confidence: 55% (low — we don't have a big edge)")
L.append("```")
L.append("")
L.append("These picks go to:")
L.append("1. A website you built at `https://true.zo.space/combos` where you can see them")
L.append("2. A Google Doc report")
L.append("3. An email summary every morning at 9 AM")
L.append("4. A pre-tip (right before game time) email at 5 PM")
L.append("")

L.append("## Step 4: CHECK YOUR WORK (The Backtest)")
L.append("")
L.append("After the game is over, the pipeline asks ESPN one more time: 'What were the final scores?' It then compares what it predicted to what really happened.")
L.append("")
L.append("Example: It said A'ja would score UNDER 38.5 PRA. She actually got 40 PRA. So that pick was WRONG.")
L.append("")
L.append("The pipeline keeps a running score of how many picks it got right. Currently the scoreboard looks like this:")
L.append("")
L.append("| Type of bet | How many we tried | How many we got right | Win rate |")
L.append("|---|---|---|---|")
L.append("| Single stat (NBA, 14 days) | 2882 picks | 1319 | 47.0% |")
L.append("| Combo prop (3 WNBA games, 3 days) | 72 legs | 19 (Under) + 17 (Over) = 36 | 50.0% |")
L.append("")
L.append("47% is bad (you lose money). 50% is break-even (no profit). 53%+ is where you start making money.")
L.append("")

L.append("---")
L.append("")

L.append("# PART 3: The 17 Scripts in Your Projects Folder")
L.append("")
L.append("Let me explain each script. Think of them as tools in a toolbox. Some are big important ones, some are little helpers.")
L.append("")

L.append("## The Big Important Ones")
L.append("")

L.append("### 1. `tc_math.py` (THE BRAIN)")
L.append("")
L.append("This is the most important file. It contains all the math for predicting player stats. It has functions like:")
L.append("")
L.append("- `project_pra()` — predict points+rebounds+assists")
L.append("- `project_pr()` — predict points+rebounds")
L.append("- `project_pa()` — predict points+assists")
L.append("- `bayesShrink()` — the 'be careful with small samples' math")
L.append("- `ceiling_recommend()` — the new 'should I bet OVER or UNDER' decision-maker")
L.append("")
L.append("Every other script that needs to predict stats imports this file. There's only ONE copy of the math. If you change it here, it changes everywhere.")
L.append("")

L.append("### 2. `daily_picks.py` (THE MORNING WORKER)")
L.append("")
L.append("This runs at 9 AM every day. It:")
L.append("1. Goes to ESPN, gets today's games")
L.append("2. Gets all the player stats from yesterday")
L.append("3. Runs them through the TC math")
L.append("4. Writes down all the picks in a folder called `Daily_Log/2026-06-10/`")
L.append("5. Sends you an email summary")
L.append("")

L.append("### 3. `dk_combos_engine.py` (THE LIVE COMBO MACHINE)")
L.append("")
L.append("This is the one running on the internet at `https://dk-combos-engine-true.zocomputer.io`. When you open the combos page, this script:")
L.append("1. Asks The Odds API for live DraftKings combo lines for tonight's games")
L.append("2. If The Odds API fails, falls back to other sources (4 different backup plans)")
L.append("3. Returns them as JSON (a list of numbers the website can read)")
L.append("")
L.append("This is where the WNBA fix was important — for 30 minutes, DraftKings combo lines for WNBA were missing, and I had to teach this script to ask the backup source.")
L.append("")

L.append("### 4. `boxscore_combo_backtest.py` (THE TRUTH-CHECKER)")
L.append("")
L.append("This is the one that uses the REAL DraftKings lines from past games (not fake ones we made up). It:")
L.append("1. Goes to The Odds API's HISTORY endpoint (which remembers what lines WERE yesterday)")
L.append("2. Goes to ESPN for the final scores")
L.append("3. Pairs them up: 'Did the player beat the line?'")
L.append("4. Writes a report")
L.append("")
L.append("This is the most important test. If we win 50% on real data, we don't make money. We need to win more.")
L.append("")

L.append("### 5. `tc_math_audit.py` (THE MATH INSPECTOR)")
L.append("")
L.append("This was built today. It runs the TC math on real pre-game projections (`proj_WNBA_*.json` files that the daily pipeline saved) and compares them to the real closing lines from `boxscore_combo_backtest_*.csv`. This showed us the BIG problem:")
L.append("")
L.append("- 9.5 points of PRA is being missed on every player")
L.append("- All 72 picks lean UNDER")
L.append("- We get 0% on the OVER, 52.8% on the UNDER")
L.append("How we use the 6-step ins")
L.append("")
L.append("**The fix is in the new `ceiling_recommend()` function in tc_math.py.** Instead of always picking UNDER, it now says 'OVER, UNDER, or PASS' based on a smarter formula.")
L.append("")

L.append("### 6. `build_tc_design.py` (THE PLANNER)")
L.append("")
L.append("This is the report-builder. It takes the audit numbers and writes a markdown document with the 6 recommendations for fixing the math. It saved `wnba_tc_design_20260610_2324.md`.")
L.append("")

L.append("## The Medium Helpers")
L.append("")

L.append("### 8. `boxscore_live_scraper.py`")
L.append("Pulls live box scores during games. Used to track 'are players actually doing what we predicted mid-game?'")
L.append("")
L.append("### 9. `player_gamelogs.py`")
L.append("Pulls the last 5 games for every player. This is where the 'average' numbers come from.")
L.append("")
L.append("### 10. `build_pregame_combos.py`")
L.append("Builds the combo picks before the game starts. Uses tc_math + dk_combos_engine together.")
L.append("")
L.append("### 11. `recompute_bayes.py`")
L.append("Recalculates the Bayesian shrinkage numbers. Run this when you have new backtest data and want to tune the math.")
L.append("")
L.append("### 12. `reconcile_picks_vs_box.py`")
L.append("Compares morning picks to actual box scores. Tells you 'we picked this player to score 25, they actually scored 30, we were wrong by 5.'")
L.append("")
L.append("### 13. `historical_odds_backtest.py`")
L.append("Older version of the backtester. Still kept around for reference.")
L.append("")

L.append("## The Build Scripts (Output Generators)")
L.append("")

L.append("### 14. `build_wnba_combos_report.py`")
L.append("Writes the WNBA combo report as a markdown file you can read or share.")
L.append("")
L.append("### 15. `build_tc_recommendations.py`")
L.append("Writes the 'what to fix' report from the audit.")
L.append("")
L.append("### 16. `build_hits_file.py`")
L.append("Makes a CSV of which picks hit and which missed.")
L.append("")

L.append("## The Long Tests")
L.append("")

L.append("### 17. `backtest_30day.py`")
L.append("The biggest test. Runs the whole pipeline over 30 days. Takes a long time, gives the most accurate numbers.")
L.append("")

L.append("---")
L.append("")

L.append("# PART 4: Where Your Pipeline Lives on the Internet")
L.append("")
L.append("You have 3 websites running:")
L.append("")
L.append("**1. `true.zo.space/nba-tc`** (the main dashboard)")
L.append("- Big screen showing today's games")
L.append("- Player projections, win probabilities, edge numbers")
L.append("- Updated in real-time")
L.append("")
L.append("**2. `true.zo.space/combos`** (the combo generator)")
L.append("- Shows all the PRA/PR/PA combo picks for tonight")
L.append("- Lets you build parlays (combine 2+ bets)")
L.append("- The page was getting a 'JSON parse error' earlier — we fixed that by teaching the engine to use the Odds API as a backup for WNBA")
L.append("")
L.append("**3. `true.zo.space/`** (the home page)")
L.append("- Private, just for you")
L.append("- Links to the other pages")
L.append("")
L.append("And 1 background service:")
L.append("")
L.append("**`dk-combos-engine-true.zocomputer.io`** (the combos server)")
L.append("- Runs 24/7")
L.append("- When your browser asks for combo lines, this server asks The Odds API and sends back the answer")
L.append("- We restarted it tonight to make sure the WNBA fix took effect")
L.append("")

L.append("---")
L.append("")

L.append("# PART 5: The Daily Schedule (The Robot's Alarm Clock)")
L.append("")
L.append("Your computer has 3 scheduled jobs, like 3 alarm clocks:")
L.append("")
L.append("| Time | What happens | What you get |")
L.append("|---|---|---|")
L.append("| 8:00 AM ET | `Scripts/refresh_daily_data.sh` | Email with yesterday's results |")
L.append("| 9:00 AM ET | `daily_picks.py` | Email with today's picks |")
L.append("| 5:00 PM ET | `daily_tip_report.py` + `generate_report.py` | Pre-tip email right before games start |")
L.append("")
L.append("These run automatically every day. You don't have to do anything.")
L.append("")

L.append("---")
L.append("")

L.append("# PART 6: The Big Problem We Just Found")
L.append("")
L.append("Today's audit found a HUGE issue:")
L.append("")
L.append("**The pipeline was 9.5 points off on every combo projection.**")
L.append("")
L.append("Imagine you're in a class and the teacher says 'Guess how many jellybeans are in the jar.' The real answer is 500. The other students guess 480, 510, 495. You guess 30. You would be wrong EVERY TIME.")
L.append("")
L.append("That's what the math was doing. It was so scared of being wrong that it always guessed way too low.")
L.append("")
L.append("Why? Two reasons:")
L.append("1. **STAT_CONS = 0.85** — this means 'multiply by 0.85' (shrink the average). That's TOO MUCH shrinkage for combo props.")
L.append("2. **WNBA minutes_norm = 0.833** — this is for the 40-minute game. But it stacks ON TOP of the 0.85, making the projection 0.71× of the average. Way too low.")
L.append("")
L.append("Example: A'ja Wilson's last 5-game average was 41 PRA. The pipeline projected 29.1 PRA. She actually got 38 PRA. The pipeline was off by 9 points!")
L.append("")
L.append("**The 6 fixes we recommend:**")
L.append("")
L.append("1. **Raise STAT_CONS from 0.85 to 0.92 for combos** — not so scared of the average")
L.append("2. **Add a ceiling function** — predict at the DK line + 0.5, only bet OVER when player's true average covers the line")
L.append("3. **Default to OVER, not UNDER** — the data shows the OVER hits more often than expected when you trust the math")
L.append("4. **Track ceiling_pct** — measure how far off we are. When it's below 95% for 3+ games, recalibrate.")
L.append("5. **Remove BLK completely** — 29% win rate is unprofitable")
L.append("6. **Add `ceiling_recommend()` field to ComboProjection** — every pick now gets a 'OVER / UNDER / PASS' label")
L.append("")

L.append("---")
L.append("")

L.append("# PART 7: The Money Side of Things")
L.append("")
L.append("Let's talk dollars. If you bet $100 on a game at -110 odds:")
L.append("- Win: you get $190 back (your $100 + $90 profit)")
L.append("- Lose: you lose your $100")
L.append("")
L.append("To make money over time, you need to win MORE than 52.4% of your bets at -110 odds. That's because of the 'juice' (the fee the betting site charges).")
L.append("")
L.append("**Current state:**")
L.append("- Single-stat WNBA: 47% (losing money slowly)")
L.append("- NBA combos: not measured yet but probably around 50%")
L.append("- WNBA combos (new audit): 50% break-even on the historical real closing lines")
L.append("")
L.append("**What 'good' looks like:**")
L.append("- 53%+ win rate on at least 100+ picks")
L.append("- That means out of every 100 bets, you win 53 and lose 47")
L.append("- At $100 each: 53 wins × $90 = $4,770 — 47 losses × $100 = $4,700 = **$70 profit per 100 bets**")
L.append("")
L.append("The whole point of the audit and the redesign is to GET to that 53% number. Right now we're at 47-50%.")
L.append("")

L.append("---")
L.append("")

L.append("# PART 8: What's Saved Where")
L.append("")
L.append("Your computer has folders for everything:")
L.append("")
L.append("**`/Projects/`** — the 17 scripts (the brain)")
L.append("")
L.append("**`/Daily_Log/2026-06-10/`** — today's picks (one folder per day)")
L.append("- `slate_NBA.json` — today's NBA games")
L.append("- `slate_WNBA.json` — today's WNBA games")
L.append("- `picks.csv` — the picks in spreadsheet format")
L.append("- `proj_WNBA_*.json` — the pre-game projections (USED FOR THE AUDIT)")
L.append("- `combos_summary.json` — the combo picks summary")
L.append("")
L.append("**`/Reports/`** — human-readable reports")
L.append("- Today we added:")
L.append("  - `boxscore_combo_backtest_20260610_2255.md` — the backtest with REAL DraftKings lines")
L.append("  - `tc_math_audit_20260610_2335.csv` — the audit data")
L.append("  - `wnba_tc_design_20260610_2335.md` — the 6 recommendations")
L.append("  - `tc_math_recommendations_20260610_2304.md` — earlier recommendations")
L.append("  - `wnba_combos_20260610_2224.md` — the WNBA combo report")
L.append("")
L.append("**`/Archives/`** — old stuff we don't need anymore but want to keep")
L.append("- `INTEGRATION_2026-06-09_obsolete/` — 21 files from the last cleanup")
L.append("")
L.append("**`/Skills/`** — the helper skills like Odds API connectors")
L.append("")
L.append("**`/Scripts/`** — the scheduled task scripts (the alarm clock code)")
L.append("")

L.append("---")
L.append("")

L.append("# PART 9: What To Do Next")
L.append("")
L.append("Here's the priority list, in order of importance:")
L.append("")
L.append("**This week:**")
L.append("1. Re-run the 14-day WNBA backtest with the new `ceiling_recommend()` function")
L.append("2. If the new function shows >52% win rate on the historical data, ship it to the live site")
L.append("3. Add the new field to the zo.space/combos page so picks now show 'OVER' or 'UNDER' or 'PASS'")
L.append("")
L.append("**Next week:**")
L.append("4. Start betting small ($10-20 per pick) to test in real life")
L.append("5. Track every bet in a spreadsheet")
L.append("6. After 50 real bets, compare your real win rate to the backtest's prediction")
L.append("")
L.append("**Next month:**")
L.append("7. Add NBA historical backtest (only WNBA has it right now)")
L.append("8. Add player-specific calibration (some players might need different CONS than others)")
L.append("9. Build a 'model drift' alert — if the win rate drops below 48% for 2 weeks, send you a text")
L.append("")
L.append("---")
L.append("")
L.append("# PART 10: The Vocabulary (Big Words, Small Meanings)")
L.append("")
L.append("| Big word | What it means |")
L.append("|---|---|")
L.append("| **TC projection** | What the math thinks the player will do |")
L.append("| **Bayesian shrinkage** | Pulling a number back toward the average when you don't have much data |")
L.append("| **Combo prop** | A bet that adds 2 or 3 stats together (like points + rebounds) |")
L.append("| **OVER / UNDER** | Whether you think the player will do MORE (over) or LESS (under) than the line |")
L.append("| **Closing line** | The final betting line right before the game starts |")
L.append("| **Line** | The number DraftKings picks — you compare your projection to it |")
L.append("| **Edge** | How much better your projection is than the line |")
L.append("| **Juice / Vig** | The fee the betting site charges (around 10% for -110 odds) |")
L.append("| **Hit rate** | Percent of bets you got right |")
L.append("| **Backtest** | Running the math on past games to see if it would have won |")
L.append("| **Real-time** | Live, updated every second |")
L.append("| **JSON** | A way to write data so computers can read it |")
L.append("| **API** | A way for two websites to talk to each other |")
L.append("| **Cron / Automation** | A scheduled task that runs automatically |")
L.append("| **Subprocess / Module** | A small program that does one job inside a bigger program |")
L.append("| **Working directory** | The folder your computer is looking at right now |")
L.append("| **Subprocess** | Running another program from inside your program |")
L.append("")
L.append("---")
L.append("")
L.append("# THE END")
L.append("")
L.append("Questions? Just text me! I can explain any part in more detail, change anything that's not working, or build new parts. The whole thing is yours to play with.")
L.append("")
L.append("(Report saved: " + str(OUT) + ")")

OUT.write_text(chr(10).join(L))
print("wrote", OUT, "lines:", len(L), "bytes:", OUT.stat().st_size)