#!/usr/bin/env python3
"""
Morning Briefing Generator for Tyson
Generates a personalized briefing and emails it to tysonjdepina76@gmail.com
"""

import requests
import json
from datetime import datetime

# Email recipient
RECIPIENT = "tysonjdepina76@gmail.com"
USER_NAME = "Tyson"

# Motivational quotes for reentry/personal growth
QUOTES = [
    '"The only way out is through." — Robert Frost',
    '"Every day is a fresh start." — Unknown',
    '"Your past does not define your future." — Unknown',
    '"Success is not final, failure is not fatal: it is the courage to continue that counts." — Winston Churchill',
    '"It is never too late to be what you might have been." — George Eliot',
    '"We may encounter defeat but we must not be defeated." — Maya Angelou',
    '"The comeback is always stronger than the setback." — Unknown',
]

def get_weather():
    """Get current weather for New Bedford, MA"""
    try:
        # Using wttr.in which is a free weather service
        response = requests.get("https://wttr.in/New+Bedford+MA?format=j1", timeout=10)
        if response.status_code == 200:
            data = response.json()
            current = data.get("current_condition", [{}])[0]
            temp_f = current.get("temp_F", ["N/A"])[0]
            condition = current.get("weatherDesc", [{}])[0].get("value", "N/A")
            
            # Get today's weather
            today = data.get("weather", [{}])[0]
            max_temp = today.get("maxtempC", ["N/A"])[0]
            min_temp = today.get("mintempC", ["N/A"])[0]
            
            return f"""**Current Conditions:** {condition}, {temp_f}°F
**Today's Forecast:** High {max_temp}°C / Low {min_temp}°C"""
    except Exception as e:
        return f"Unable to fetch weather (Error: {str(e)})"

def get_community_news():
    """Search for Cape Verdean community news and events"""
    news_items = []
    
    try:
        # Search for Cape Verdean community news
        search_url = "https://ddg-api.ht Services/v1/news"
        params = {
            "query": "Cape Verdean community New Bedford Massachusetts events",
            "count": 5
        }
        response = requests.get(search_url, params=params, timeout=10)
        if response.status_code == 200:
            results = response.json()
            for item in results[:3]:
                news_items.append(f"- [{item.get('title', 'News')}]({item.get('url', '#')})")
    except:
        pass
    
    if not news_items:
        return "- No recent Cape Verdean community news found. Check local New Bedford community boards for events."
    
    return "\n".join(news_items)

def generate_briefing():
    """Generate the full morning briefing"""
    import random
    
    weather = get_weather()
    community_news = get_community_news()
    quote = random.choice(QUOTES)
    
    briefing = f"""# ☀️ Good Morning, {USER_NAME}!

Here's your personalized morning briefing for {datetime.now().strftime('%A, %B %d, %Y')}.

---

## 🌤️ New Bedford Weather

{weather}

---

## 📰 Cape Verdean Community News & Events

{community_news}

---

## 👨‍👩‍👧‍👦 Children's Milestones

*Note: Update this section with any recent milestones from your children ages 25, 23, and 20.*

Here's a gentle prompt to reflect on:
- What accomplishments have your children made recently?
- Any new jobs, education milestones, or personal achievements to celebrate?
- How can you support their growth this week?

---

## 💪 Motivational Quote

>{quote}

---

## 🎯 Reentry Goals & Job-Search Resources

**Remember your goals:**
- Finding stable employment
- Rebuilding relationships with family
- Contributing to your community
- Personal growth and development

**Job-Search Resources for Returning Citizens:**

1. **Massachusetts Reentry Hotline:** Dial 211 (24/7 support)
2. **Federal Bonding Program:** Helps employers hire returning citizens
3. **New Bedford Career Center:** 1213 Purchase St, New Bedford, MA | (508) 990-4000
4. **Massachusetts Career Centers:** www.mass.gov/career-centers
5. **expunge.io:** Free online expungement guide for Massachusetts
6. **The Last Mile:** Prison-to-workforce programs in tech
7. **Center for Employment Opportunities (CEO):** CEO.org

**Remember:** You have 24 years of life experience, wisdom, and resilience. Employers value that. Keep pushing forward!

---

*This briefing was generated by Zo — your personal AI assistant.*

*To update your preferences or children information, just let me know!*
"""
    
    return briefing

def send_email(subject, body):
    """Send email using the Zo email system"""
    # This will be handled by the scheduled agent using send_email_to_user tool
    pass

if __name__ == "__main__":
    briefing = generate_briefing()
    print(briefing)
    print("\n--- END OF BRIEFING ---")
    print(f"Would be sent to: {RECIPIENT}")
