# calibrated_thresholds.py – Auto-generated by recalibrate_thresholds.py
# Generated: 2026-08-18T00:39:50.380558

THRESHOLDS = {
    "mlb": {
        "OVER": 0.17000000000000004,
        "UNDER": -0.5
    },
    "wnba": {
        "OVER": 0.5,
        "UNDER": -0.5
    }
}

# Convenience access
MLB_OVER = THRESHOLDS['mlb']['OVER']
MLB_UNDER = THRESHOLDS['mlb']['UNDER']
WNBA_OVER = THRESHOLDS['wnba']['OVER']
WNBA_UNDER = THRESHOLDS['wnba']['UNDER']
