#!/usr/bin/env python3
"""
recalibrate_thresholds.py – Dynamically recalibrate directional thresholds
based on recent graded picks.

Usage:
    python3 src/recalibrate_thresholds.py [--days 7] [--target 0.55]
"""

import sqlite3
import json
import argparse
from pathlib import Path
from datetime import datetime, timedelta
import pandas as pd
import numpy as np

DB_PATH = Path("data/picks.db")
THRESHOLDS_FILE = Path("src/calibrated_thresholds.py")
REPORT_DIR = Path("Daily_Log")
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# Defaults
DEFAULT_DAYS = 7
DEFAULT_TARGET = 0.55  # 55% hit rate target
MIN_THRESHOLD = 0.01
MAX_THRESHOLD = 0.50

def fetch_graded_picks(days: int) -> pd.DataFrame:
    """Fetch all graded picks from the last N days."""
    cutoff = (datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d')
    conn = sqlite3.connect(DB_PATH)
    query = f"""
        SELECT league, direction, edge, hit
        FROM picks
        WHERE hit IS NOT NULL
          AND date >= '{cutoff}'
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    return df

def compute_optimal_threshold(df: pd.DataFrame, league: str, direction: str, target: float) -> float:
    """
    For a given league/direction, find the edge threshold that yields
    a cumulative hit rate >= target when including only picks with edge
    >= threshold (for OVER) or edge <= threshold (for UNDER).
    """
    sub = df[(df['league'] == league) & (df['direction'] == direction)]
    if sub.empty:
        return None

    if direction == 'OVER':
        sub = sub.sort_values('edge', ascending=False)
    else:
        sub = sub.sort_values('edge', ascending=True)

    sub['cum_hits'] = sub['hit'].cumsum()
    sub['cum_count'] = range(1, len(sub) + 1)
    sub['cum_hit_rate'] = sub['cum_hits'] / sub['cum_count']

    idx = sub[sub['cum_hit_rate'] >= target].index
    if not idx.empty:
        threshold = sub.loc[idx[0], 'edge']
        return threshold
    else:
        best_idx = sub['cum_hit_rate'].idxmax()
        return sub.loc[best_idx, 'edge']

def generate_thresholds(df: pd.DataFrame, target: float) -> dict:
    """Calculate thresholds for all leagues and directions."""
    thresholds = {}
    leagues = df['league'].unique()
    for league in leagues:
        thresholds[league] = {}
        for direction in ['OVER', 'UNDER']:
            threshold = compute_optimal_threshold(df, league, direction, target)
            if threshold is None:
                if league == 'mlb':
                    thresholds[league][direction] = 0.30 if direction == 'OVER' else -0.06
                elif league == 'wnba':
                    thresholds[league][direction] = 0.15 if direction == 'OVER' else -0.50
                else:
                    thresholds[league][direction] = 0.10 if direction == 'OVER' else -0.10
            else:
                if direction == 'OVER':
                    thresholds[league][direction] = max(MIN_THRESHOLD, min(MAX_THRESHOLD, threshold))
                else:
                    thresholds[league][direction] = -max(MIN_THRESHOLD, min(MAX_THRESHOLD, -threshold))
    return thresholds

def update_thresholds_file(thresholds: dict):
    """Write the new thresholds to src/calibrated_thresholds.py."""
    content = f'''# calibrated_thresholds.py – Auto-generated by recalibrate_thresholds.py
# Generated: {datetime.now().isoformat()}

THRESHOLDS = {json.dumps(thresholds, indent=4)}

# Convenience access
MLB_OVER = THRESHOLDS['mlb']['OVER']
MLB_UNDER = THRESHOLDS['mlb']['UNDER']
WNBA_OVER = THRESHOLDS['wnba']['OVER']
WNBA_UNDER = THRESHOLDS['wnba']['UNDER']
'''
    with open(THRESHOLDS_FILE, 'w') as f:
        f.write(content)
    print(f"✅ Updated thresholds file: {THRESHOLDS_FILE}")

def save_report(thresholds: dict, days: int, target: float, df: pd.DataFrame):
    """Save a JSON report of the recalibration run."""
    report = {
        'timestamp': datetime.now().isoformat(),
        'days_used': days,
        'target_hit_rate': target,
        'thresholds': thresholds,
        'data_summary': {}
    }
    for league in df['league'].unique():
        report['data_summary'][league] = {
            'total': len(df[df['league'] == league]),
            'over_picks': len(df[(df['league'] == league) & (df['direction'] == 'OVER')]),
            'under_picks': len(df[(df['league'] == league) & (df['direction'] == 'UNDER')]),
            'over_hit_rate': round(df[(df['league'] == league) & (df['direction'] == 'OVER')]['hit'].mean(), 3),
            'under_hit_rate': round(df[(df['league'] == league) & (df['direction'] == 'UNDER')]['hit'].mean(), 3),
        }
    report_path = REPORT_DIR / f"recalibration_{datetime.now().strftime('%Y-%m-%d_%H%M%S')}.json"
    with open(report_path, 'w') as f:
        json.dump(report, f, indent=2)
    print(f"📄 Report saved to {report_path}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--days', type=int, default=DEFAULT_DAYS, help='Number of past days to analyze')
    parser.add_argument('--target', type=float, default=DEFAULT_TARGET, help='Target cumulative hit rate (e.g., 0.55)')
    args = parser.parse_args()

    print(f"📊 Recalibrating thresholds using last {args.days} days of graded picks, target hit rate = {args.target*100:.1f}%")
    df = fetch_graded_picks(args.days)
    if df.empty:
        print("❌ No graded picks found. Aborting.")
        return

    thresholds = generate_thresholds(df, args.target)
    update_thresholds_file(thresholds)
    save_report(thresholds, args.days, args.target, df)

    print("\n✅ New thresholds:")
    for league, dirs in thresholds.items():
        print(f"  {league.upper()}: OVER = {dirs['OVER']:.3f}, UNDER = {dirs['UNDER']:.3f}")

if __name__ == "__main__":
    main()
